// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MedicineService.proto

package org.baeldung.grpc;

public interface MedicineRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.baeldung.grpc.MedicineRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string medicineId = 1;</code>
   * @return The medicineId.
   */
  String getMedicineId();
  /**
   * <code>string medicineId = 1;</code>
   * @return The bytes for medicineId.
   */
  com.google.protobuf.ByteString
      getMedicineIdBytes();
}
