// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MedicineService.proto

package org.baeldung.grpc;

public interface MedicineResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.baeldung.grpc.MedicineResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
